//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Windows_Uomi_App.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Windows_Uomi_App.Languages.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel_Text {
            get {
                return ResourceManager.GetString("btnCancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        internal static string btnClearFilter_text {
            get {
                return ResourceManager.GetString("btnClearFilter_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string btnSave_Text {
            get {
                return ResourceManager.GetString("btnSave_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete customer: &apos;{0}&apos;?.
        /// </summary>
        internal static string confirm_delete_customer {
            get {
                return ResourceManager.GetString("confirm_delete_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer.
        /// </summary>
        internal static string confirm_delete_customer_caption {
            get {
                return ResourceManager.GetString("confirm_delete_customer_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete transaction at &apos;{0}&apos; of {1}?.
        /// </summary>
        internal static string confirm_delete_transaction {
            get {
                return ResourceManager.GetString("confirm_delete_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Transaction.
        /// </summary>
        internal static string confirm_delete_transaction_caption {
            get {
                return ResourceManager.GetString("confirm_delete_transaction_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string credit {
            get {
                return ResourceManager.GetString("credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer &apos;{0}&apos; deleted successfully..
        /// </summary>
        internal static string customer_deleted {
            get {
                return ResourceManager.GetString("customer_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Export Failed!.
        /// </summary>
        internal static string db_export_failed {
            get {
                return ResourceManager.GetString("db_export_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Exported Successfully!.
        /// </summary>
        internal static string db_exported_successfully {
            get {
                return ResourceManager.GetString("db_exported_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string debit {
            get {
                return ResourceManager.GetString("debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the amount you entered.
        /// </summary>
        internal static string Erroneous_Amount {
            get {
                return ResourceManager.GetString("Erroneous_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string frmAbout_Caption {
            get {
                return ResourceManager.GetString("frmAbout_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Data.
        /// </summary>
        internal static string frmCustomerData_Caption {
            get {
                return ResourceManager.GetString("frmCustomerData_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Ledger.
        /// </summary>
        internal static string frmCustomerLedger_Caption {
            get {
                return ResourceManager.GetString("frmCustomerLedger_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uomi - Because, you owe me!.
        /// </summary>
        internal static string frmMain_Caption {
            get {
                return ResourceManager.GetString("frmMain_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string frmTransaction_Caption {
            get {
                return ResourceManager.GetString("frmTransaction_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Data.
        /// </summary>
        internal static string gbxConctactData_Text {
            get {
                return ResourceManager.GetString("gbxConctactData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string gbxCustomer_Text {
            get {
                return ResourceManager.GetString("gbxCustomer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Data.
        /// </summary>
        internal static string gbxCustomerData_Text {
            get {
                return ResourceManager.GetString("gbxCustomerData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        internal static string gbxCustomerType_Text {
            get {
                return ResourceManager.GetString("gbxCustomerType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string gbxDetails_Text {
            get {
                return ResourceManager.GetString("gbxDetails_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string gbxFilter_text {
            get {
                return ResourceManager.GetString("gbxFilter_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Data.
        /// </summary>
        internal static string gbxRetailData_Text {
            get {
                return ResourceManager.GetString("gbxRetailData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Type.
        /// </summary>
        internal static string gbxTransactionType_Text {
            get {
                return ResourceManager.GetString("gbxTransactionType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Data.
        /// </summary>
        internal static string gbxWholesaleData_Text {
            get {
                return ResourceManager.GetString("gbxWholesaleData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string gvwCustomers_addressDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwCustomers_addressDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string gvwCustomers_balanceDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwCustomers_balanceDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        internal static string gvwCustomers_idDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwCustomers_idDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string gvwCustomers_nameDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwCustomers_nameDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        internal static string gvwCustomers_phonenumberDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwCustomers_phonenumberDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string gvwTransactions_commentDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwTransactions_commentDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string gvwTransactions_localizedAmountDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwTransactions_localizedAmountDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp.
        /// </summary>
        internal static string gvwTransactions_timestampDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwTransactions_timestampDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string gvwTransactions_transTypeDataGridViewTextBoxColumn_text {
            get {
                return ResourceManager.GetString("gvwTransactions_transTypeDataGridViewTextBoxColumn_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string lblAddress_Text {
            get {
                return ResourceManager.GetString("lblAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string lblAmount_Text {
            get {
                return ResourceManager.GetString("lblAmount_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string lblBalance_Text {
            get {
                return ResourceManager.GetString("lblBalance_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        internal static string lblBusinessName_Text {
            get {
                return ResourceManager.GetString("lblBusinessName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string lblCustomer_Text {
            get {
                return ResourceManager.GetString("lblCustomer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        internal static string lblDate_Text {
            get {
                return ResourceManager.GetString("lblDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string lblFirstName_Text {
            get {
                return ResourceManager.GetString("lblFirstName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lblLastName_Text {
            get {
                return ResourceManager.GetString("lblLastName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonenumber.
        /// </summary>
        internal static string lblPhonenumber_Text {
            get {
                return ResourceManager.GetString("lblPhonenumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT Number.
        /// </summary>
        internal static string lblVatNumber_Text {
            get {
                return ResourceManager.GetString("lblVatNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string mnuItemAbout_Text {
            get {
                return ResourceManager.GetString("mnuItemAbout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credit (We owe money to the customer).
        /// </summary>
        internal static string mnuItemAddCredit_Text {
            get {
                return ResourceManager.GetString("mnuItemAddCredit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string mnuItemAddCustomer_Text {
            get {
                return ResourceManager.GetString("mnuItemAddCustomer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Debit (Customer owes us money).
        /// </summary>
        internal static string mnuItemAddDebit_Text {
            get {
                return ResourceManager.GetString("mnuItemAddDebit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string mnuItemCustomers_Text {
            get {
                return ResourceManager.GetString("mnuItemCustomers_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer.
        /// </summary>
        internal static string mnuItemDeleteCustomer_Text {
            get {
                return ResourceManager.GetString("mnuItemDeleteCustomer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Transaction.
        /// </summary>
        internal static string mnuItemDeleteTransaction_Text {
            get {
                return ResourceManager.GetString("mnuItemDeleteTransaction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        internal static string mnuItemEditCustomer_Text {
            get {
                return ResourceManager.GetString("mnuItemEditCustomer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Transaction.
        /// </summary>
        internal static string mnuItemEditTransaction_Text {
            get {
                return ResourceManager.GetString("mnuItemEditTransaction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to .json file.
        /// </summary>
        internal static string mnuItemExport2Json_text {
            get {
                return ResourceManager.GetString("mnuItemExport2Json_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language and Locale.
        /// </summary>
        internal static string mnuItemLanguage_Text {
            get {
                return ResourceManager.GetString("mnuItemLanguage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string mnuItemSettings_Text {
            get {
                return ResourceManager.GetString("mnuItemSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string mnuItemTransaction_Text {
            get {
                return ResourceManager.GetString("mnuItemTransaction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Customer.
        /// </summary>
        internal static string mnuItemViewCustomer_Text {
            get {
                return ResourceManager.GetString("mnuItemViewCustomer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Customer.
        /// </summary>
        internal static string rdbRetail_Text {
            get {
                return ResourceManager.GetString("rdbRetail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Customer.
        /// </summary>
        internal static string rdbWholesale_Text {
            get {
                return ResourceManager.GetString("rdbWholesale_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string tbpCustomers_Text {
            get {
                return ResourceManager.GetString("tbpCustomers_Text", resourceCulture);
            }
        }
    }
}
